name: check license

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
    paths-ignore:
      - '.github/**'
      - '*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '*.md'

jobs:
  check_license:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: run make add_license
        run: make check_license
